### get all data
GET http://localhost:8000/api/ext/awf-extension/get-default-sequence
Accept: application/json
Content-Type: application/json

### get data by WC
GET https://oeem.awf.hu/api/ext/awf-extension/get-sequence/EL01/A
Accept: application/json
Content-Type: application/json

{
  "side": "L",
  "limit": 1,
  "no_change": "true"
}

### get default preparation panel
GET http://localhost:8003/api/ext/awf-extension/preparation-panel/default
Accept: application/json
Content-Type: application/json

### get welder data
GET http://localhost:8000/api/ext/awf-extension/sequence/welder/B/HB01
Accept: application/json
Content-Type: application/json