### get features of a given product by machine
POST localhost:8000/api/ext/awf-extension/product-feature/show
Accept: application/json
Content-Type: application/json

{
  "productCode": ""
}

### check if selected color is right
POST localhost:8000/api/ext/awf-extension/product-feature/check
Accept: application/json
Content-Type: application/json

{
  "productCode": "",
  "color": ""
}