### check serial
POST https://oeem.awf.hu/api/ext/awf-extension/order/check-serial/11
Accept: application/json
Content-Type: application/json

{
  "serial": "HW01000242439"
}

### check serial - test
POST http://localhost:8003/api/ext/awf-extension/order/check-serial/7
Accept: application/json
Content-Type: application/json

{
  "serial": "HW01000220353"
}