### check if it is the next product
POST https://oeem.awf.hu/api/ext/awf-extension/product/check
Accept: application/json
Content-Type: application/json

{
  "dashboard": "16",
  "serial": "HW01000242393"
}

### check if it is the next product - teszt
POST localhost:8000/api/ext/awf-extension/product/check
Accept: application/json
Content-Type: application/json

{
  "dashboard": "16",
  "serial": "HW01000242012"
}