### move sequence
POST https://oeem.awf.hu/api/ext/awf-extension/move-sequence
Accept: application/json
Content-Type: application/json

{
  "WCSHNA": "HBJ01",
  "SEQUID": 212605
}

### move sequence - test
POST http://oeem.local/api/ext/awf-extension/move-sequence
Accept: application/json
Content-Type: application/json

{
  "WCSHNA": "VBJ01",
  "SEQUID": 150583,
  "pillar": "B"
}

### order changeonjs
POST http://localhost:8000/api/dashboard/2/order/saveOrderChange
Accept: application/json
Content-Type: application/json

{
  "unassignedOrders": {},
  "assignedOrders": [
    {
      "ORCODE": "2745165_458710_F46B16101_2",
      "RNREPN": "2745165_458710_F46B16101_2-KAB01-PRB",
      "RNOLMU": 1,
      "type": "assigned"
    }
  ],
  "isChecklist": false,
  "users": [
    1
  ]
}